server:
  port: 8081

spring:
  application:
    name: user

eureka:
  instance:
    hostname: localhost
  client:
    reigster-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"