server:
  port: 8081
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        -id: user
        uri: http://localhost:8082
        predicates:
          - Methods: GET,POST
eureka:
  instance:
    hostname: localhost
  client:
    reigster-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka

