spring:
  port: 8080
  application:
    name: registry
eureka:
  instance:
    hostname: localhost
  client:
    reigster-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka